# Generated by Django 2.0.6 on 2018-06-12 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'open'), ('PROGRESS', 'progress'), ('PENDING', 'pending'), ('HOLD', 'hold'), ('REOPEN', 'reopen'), ('RESOLVED', 'resolved'), ('CLOSED', 'closed')], default='pending', max_length=155),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assign', to=settings.AUTH_USER_MODEL),
        ),
    ]
